export const salesPoints = [
  { value: 'ExcellentLooks', label: 'ルックス抜群', no: '01' },
  { value: 'ExcellentStyle', label: 'スタイル抜群', no: '02' },
  { value: 'ExcellentService', label: 'サービス抜群', no: '03' },
  { value: 'HighSensitivity', label: '感度抜群', no: '04' },
  { value: 'Amateur', label: '素人', no: '05' },
  { value: 'BigBreasts', label: '巨乳', no: '06' },
  { value: 'Slender', label: 'スレンダー', no: '07' },
  { value: 'Marshmallow', label: 'ぷよっ子', no: '08' },
  { value: 'Petite', label: '小柄', no: '09' },
  { value: 'Tall', label: '長身', no: '10' },
  { value: 'NiceBreasts', label: '美乳', no: '11' },
  { value: 'NiceLegs', label: '美脚', no: '12' },
  { value: 'ShavedPussy', label: 'パイパン', no: '13' },
  { value: 'Cheerful', label: '明るい', no: '14' },
  { value: 'Comforting', label: '癒し系', no: '15' },
  { value: 'Arouse', label: '責め好き', no: '16' },
  { value: 'Passive ', label: '受身好き', no: '17' },
  { value: 'Anal', label: 'アナル', no: '19' },
  { value: 'Mania', label: 'マニア', no: '20' },
  { value: 'Normal', label: '普通', no: '21' },
  { value: 'Glamor', label: 'グラマー', no: '22' },
  { value: 'Chubby', label: 'ぽっちゃり', no: '23' },
  { value: 'Gal', label: 'ギャル系', no: '24' },
  { value: 'Model', label: 'モデル系', no: '25' },
  { value: 'Student', label: '現役学生', no: '26' },
  { value: 'PornActress', label: 'セクシー女優', no: '27' },
  { value: 'Mixed', label: 'ハーフ', no: '28' },
  { value: 'AnimeVoice', label: 'アニメ声', no: '29' },
  { value: 'BlackHair', label: '黒髪', no: '30' },
  { value: 'Shemale', label: 'ニューハーフ', no: '31' },
  { value: 'NipplePink', label: '乳首ピンク', no: '32' },
  { value: 'BigAreola', label: '乳輪大きい', no: '33' },
  { value: 'SpoiledChild', label: '甘えん坊', no: '34' },
  { value: 'Natural', label: '天然', no: '35' },
  { value: 'Tsundere', label: 'ツンデレ', no: '36' },
  { value: 'Calm', label: 'おっとり', no: '37' },
  { value: 'Shy', label: '恥ずかしがり屋', no: '38' },
  { value: 'Friendly', label: '人懐っこい', no: '39' },
  { value: 'Erotic', label: 'エロい', no: '40' },
  { value: 'Synchrony', label: '空気を読む', no: '41' },
  { value: 'Geek', label: 'オタク', no: '42' },
  { value: 'Reliable', label: 'しっかり者', no: '43' },
  { value: 'Squirting', label: '潮吹き', no: '44' },
  { value: 'Masochist', label: 'ドM', no: '45' },
  { value: 'Sadist', label: 'ドS・女王様', no: '46' },
  { value: 'Kinky', label: '変態', no: '47' },
  { value: 'Talkative', label: '話し好き', no: '48' },
  { value: 'Listener', label: '聞き上手', no: '49' },
  { value: 'BreastMilk', label: '母乳', no: '50' },
  { value: 'BreastSex', label: 'パイズリ', no: '51' },
  { value: 'HolyWater', label: '聖水', no: '52' },
  { value: 'Glod', label: '黄金', no: '53' },
  { value: 'NoSmoking', label: '喫煙しない', no: '54' },
  { value: 'NiceButt', label: '美尻', no: '55' },
  { value: 'Lesbian', label: 'レズビアン', no: '56' },
]



// export const salesPoints = {
//   1: 'ルックス抜群',
//   2: 'スタイル抜群',
//   3: 'サービス抜群',
//   4: '感度抜群',
//   5: '素人',
//   6: '巨乳',
//   7: 'スレンダー',
//   8: 'ぷよっ子',
//   9: '小柄',
//   10: '長身',
//   11: '美乳',
//   12: '美脚',
//   13: 'パイパン',
//   14: '明るい',
//   15: '癒し系',
//   16: '責め好き',
//   17: '受身好き',
//   19: 'ア○ル',
//   20: 'マニア',
//   21: '普通',
//   22: 'グラマー',
//   23: 'ぽっちゃり',
//   24: 'ギャル系',
//   25: 'モデル系',
//   26: '現役学生',
//   27: 'セクシー女優',
//   28: 'ハーフ',
//   29: 'アニメ声',
//   30: '黒髪',
//   31: 'ニューハーフ',
//   32: '乳首ピンク',
//   33: '乳輪大きい',
//   34: '甘えん坊',
//   35: '天然',
//   36: 'ツンデレ',
//   37: 'おっとり',
//   38: '恥ずかしがり屋',
//   39: '人懐っこい',
//   40: 'エロい',
//   41: '空気を読む',
//   42: 'オタク',
//   43: 'しっかり者',
//   44: '潮吹き',
//   45: 'ドM',
//   46: 'ドS・女王様',
//   47: '変態',
//   48: '話し好き',
//   49: '聞き上手',
//   50: '母乳',
//   51: 'パイズリ',
//   52: '聖水',
//   53: '黄金',
//   54: '喫煙しない',
//   55: '美尻',
//   56: 'レズビアン',
// }